### ISSUE TITLE
Single Table Inheritance

### ISSUE THREAD

**Issue by stephenrichards** [viafintech/tidus#19]
I am having problems generating the views for models using Single Table Inheritance - it's trying to generate two views.  Am going to try to get round this by skipping_anonymisation for all classes except one that share a table.

**Comment by tobischo** [comment]
Hello Stephen,
`skip_anonymization` is the recommended way to handle this.
Unfortunately the magic of automatically enabling it for every model comes with the side effect of not being great with single table inheritance.

Please let us know if you require additional support.

**Comment by stephenrichards** [comment]
also, we have an ApplicationRecord which derives from ActiveRecord::Base, and every model derives from that.  It's an abstract class, so doesn't have a table name, so the generate_view and clear_view tasks fail silently.  I'll fork the repo and put in a change request for that, as it's pretty standard for all new rails projects

**Comment by tobischo** [comment]
Hi Stephen,
you are right, newer Rails apps use ApplicationRecord, however we do not only care to support newer applications.
For example we are using sinatra apps with ActiveRecord and without an ApplicationRecord class.
For any such change I'd therefore expect the base class to be configurable

**Comment by tobischo** [comment]
Closing this issue as we have not heard back with more details for almost a year
